services:
  web:
    image: rajendrasingh23012005/fake_product_detector-web:multistage
    #build: .
    # image: rajendrasingh23012005/fake_product_detector-web:latest
    container_name: fake-product-container
    env_file:
      - .env
    ports:
      - "8000:8000"

