# Generated by Django 5.2.6 on 2026-02-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0005_passwordresettoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodproduct",
            name="barcode_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="foodproduct",
            name="detailed_analysis",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="foodproduct",
            name="failure_reasons",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="foodproduct",
            name="final_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="foodproduct",
            name="logo_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="foodproduct",
            name="ocr_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="foodproduct",
            name="packaging_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
