# Generated by Django 5.2.6 on 2026-02-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0006_foodproduct_barcode_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodproduct",
            name="user_report",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
