# Generated by Django 4.2 on 2026-03-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0008_userfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('upload', 'Image Upload'), ('analysis', 'Product Analysis'), ('profile_update', 'Profile Update'), ('register', 'User Registration'), ('password_reset', 'Password Reset'), ('feedback', 'Feedback Submitted')], max_length=20),
        ),
    ]
